name: Purge cache

on:
  workflow_dispatch:
  workflow_call:

jobs:
  purge-cache:
    name: Purge cache
    runs-on: ubuntu-latest

    steps:
      - uses: fjogeleit/http-request-action@551353b829c3646756b2ec2b3694f819d7957495 # v2
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache"
          method: "POST"
          bearerToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
          data: '{ "purge_everything": true }'
          retry: 3
